version: "3.7"
services:
  mysql:
    image: mysql:8.0
    container_name: pbl6_fake_news
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: PBL6
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_PASSWORD: admin1234
      MYSQL_USER: admin22
      SERVICE_TAGS: dev 
      SERVICE_NAME: mysql
    volumes:
      - pbl6_fake_news:/var/lib/mysql
networks:
  dockerproject:
    driver: bridge
volumes:
  pbl6_fake_news:
    driver: local