# Generated by Django 4.1.12 on 2024-01-02 09:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent_comment_id',  
            field=models.IntegerField(null=True),
        ),
    ]
