# Generated by Django 4.1.12 on 2023-10-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20231012_2301'),
    ]

    operations = [
    ]
