# Generated by Django 4.1.12 on 2023-11-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_comments_total_like_remove_news_total_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='label',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
