# Generated by Django 4.1.12 on 2023-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(db_collation='utf8mb4_unicode_ci'),
        ),
    ]
