# Generated by Django 4.1.12 on 2024-01-03 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_parent_comment_comments_parent_comment_id"),
        ("news", "0006_alter_news_created_at_alter_news_updated_at"),
    ]

    operations = []
