# Generated by Django 4.1.12 on 2023-10-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0001_initial'),
    ]

    operations = [
    ]
