# Generated by Django 4.1.12 on 2023-11-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_account_total_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='total_follow',
        ),
    ]
