# Generated by Django 4.1.12 on 2023-10-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0002_auto_20231021_2347'),
    ]

    operations = [
    ]
