# Generated by Django 4.1.12 on 2023-10-10 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_site', '0004_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
    ]
